#############################################################################
####### EXAMPLE use of the NGram model. This is meant for reference.
####### Change directory variables as necessary.
#############################################################################

OUTPUT_DIR= # a directory for saving reordered output
MODEL_DIR= # a directory for saving model files
REPO_DIR= # path to the repo
DATA_DIR=${REPO_DIR}/datasets # change this if you moved the datasets directory generated by the provided preprocessing scripts
TEMP_DIR= # a temp directory (for KenLM, BLEU script, etc.)
OUTPUT_LOG_FILE= # a file in which to save logging information (this should already exist, as lines will be appended below)


#### create 5-gram LM
# for BNP
lmplz -o 5 -S 3145728K -T ${TEMP_DIR} <${DATA_DIR}/"zgen_data_npsyms_freq3_unkUNK/npsyms/train_words_with_np_symbols_no_eos.txt" >${MODEL_DIR}/LM5_noeos_withnpsyms_freq3_unkUNK.arpa

# no BNP
lmplz -o 5 -S 3145728K -T ${TEMP_DIR} <${DATA_DIR}/"zgen_data_npsyms_freq3_unkUNK/no_npsyms/train_words_no_eos.txt" >${MODEL_DIR}/LM5_noeos_no_npsyms_freq3_unkUNK.arpa

#### create 1-gram LM
# for BNP
lmplz -o 1 -S 3145728K -T ${TEMP_DIR} --discount_fallback <${DATA_DIR}/"zgen_data_npsyms_freq3_unkUNK/npsyms/train_words_with_np_symbols_no_eos.txt" >${MODEL_DIR}/LM1_noeos_withnpsyms_freq3_unkUNK.arpa

# no BNP
lmplz -o 1 -S 3145728K -T ${TEMP_DIR} --discount_fallback <${DATA_DIR}/"zgen_data_npsyms_freq3_unkUNK/no_npsyms/train_words_no_eos.txt" >${MODEL_DIR}/LM1_noeos_nonpsyms_freq3_unkUNK.arpa



#############################################################################
####### NGram model with future costs (rows 2 and 4 of Table 2) on validation
#############################################################################


SPLIT_NAME=valid
for BEAM_SIZE in 1 10 64 128 256 512;
do

    ### with BNP:
    LABEL=NGRAM_FUTURE_BNP_${SPLIT_NAME}_BEAM${BEAM_SIZE}
    echo $LABEL

    OUTPUT_FILE=${OUTPUT_DIR}/output_${SPLIT_NAME}_with_npsyms_futurecosts_beam${BEAM_SIZE}_lm5_FIXED
    FUTURE_MODEL=${MODEL_DIR}/LM1_noeos_withnpsyms_freq3_unkUNK.arpa

    python ${REPO_DIR}/ngram/ngram_decoder.py ${MODEL_DIR}/LM5_noeos_withnpsyms_freq3_unkUNK.arpa ${DATA_DIR}/zgen_data_npsyms_freq3_unkUNK/npsyms/${SPLIT_NAME}_words_with_np_symbols_shuffled_no_eos.txt ${BEAM_SIZE} --future ${FUTURE_MODEL} >${OUTPUT_FILE}.txt


    python ${REPO_DIR}/data/postprocessing/randomly_replace_unkUNK.py \
    --generated_reordering_with_unk ${OUTPUT_FILE}.txt \
    --gold_unprocessed ${DATA_DIR}/zgen_data_gold/${SPLIT_NAME}_words_ref_npsyms.txt \
    --gold_processed ${DATA_DIR}/zgen_data_npsyms_freq3_unkUNK/npsyms/${SPLIT_NAME}_words_with_np_symbols_no_eos.txt \
    --out_file ${OUTPUT_FILE}_removed_unk.txt \
    --remove_npsyms

    echo "####" >> ${OUTPUT_LOG_FILE}
    echo ${LABEL} >> ${OUTPUT_LOG_FILE}

    ${REPO_DIR}/analysis/eval/zgen_bleu/ScoreBLEU.sh -t ${OUTPUT_FILE}_removed_unk.txt -r ${DATA_DIR}/zgen_data_gold/${SPLIT_NAME}_words_ref.txt -odir ${TEMP_DIR} >> ${OUTPUT_LOG_FILE}


    ### without BNP:
    LABEL=NGRAM_FUTURE_NOBNP_${SPLIT_NAME}_BEAM${BEAM_SIZE}
    echo $LABEL

    OUTPUT_FILE=${OUTPUT_DIR}/output_${SPLIT_NAME}_no_npsyms_futurecosts_beam${BEAM_SIZE}_lm5_FIXED
    FUTURE_MODEL=${MODEL_DIR}/LM1_noeos_nonpsyms_freq3_unkUNK.arpa

    python ${REPO_DIR}/ngram/ngram_decoder.py ${MODEL_DIR}/LM5_noeos_no_npsyms_freq3_unkUNK.arpa ${DATA_DIR}/zgen_data_npsyms_freq3_unkUNK/no_npsyms/${SPLIT_NAME}_words_fullyshuffled_no_eos.txt ${BEAM_SIZE} --future ${FUTURE_MODEL} >${OUTPUT_FILE}.txt


    python ${REPO_DIR}/data/postprocessing/randomly_replace_unkUNK.py \
    --generated_reordering_with_unk ${OUTPUT_FILE}.txt \
    --gold_unprocessed ${DATA_DIR}/zgen_data_gold/${SPLIT_NAME}_words_ref.txt \
    --gold_processed ${DATA_DIR}/zgen_data_npsyms_freq3_unkUNK/no_npsyms/${SPLIT_NAME}_words_no_eos.txt \
    --out_file ${OUTPUT_FILE}_removed_unk.txt \
    --remove_npsyms

    echo "####" >> ${OUTPUT_LOG_FILE}
    echo ${LABEL} >> ${OUTPUT_LOG_FILE}

    ${REPO_DIR}/analysis/eval/zgen_bleu/ScoreBLEU.sh -t ${OUTPUT_FILE}_removed_unk.txt -r ${DATA_DIR}/zgen_data_gold/${SPLIT_NAME}_words_ref.txt -odir ${TEMP_DIR} >> ${OUTPUT_LOG_FILE}

done

#############################################################################
####### An example without future costs:
####### NGram model without future costs on validation, beam 64
#############################################################################

#######
SPLIT_NAME=valid
BEAM_SIZE=64

LABEL=NGRAM_NOFUTURE_NOBNP_${SPLIT_NAME}_BEAM${BEAM_SIZE}
echo $LABEL

OUTPUT_FILE=${OUTPUT_DIR}/output_${SPLIT_NAME}_no_npsyms_nofuturecosts_beam${BEAM_SIZE}_lm5_FIXED
FUTURE_MODEL=""

python ${REPO_DIR}/ngram/ngram_decoder.py ${MODEL_DIR}/LM5_noeos_no_npsyms_freq3_unkUNK.arpa ${DATA_DIR}/zgen_data_npsyms_freq3_unkUNK/no_npsyms/${SPLIT_NAME}_words_fullyshuffled_no_eos.txt ${BEAM_SIZE} >${OUTPUT_FILE}.txt


python ${REPO_DIR}/data/postprocessing/randomly_replace_unkUNK.py \
--generated_reordering_with_unk ${OUTPUT_FILE}.txt \
--gold_unprocessed ${DATA_DIR}/zgen_data_gold/${SPLIT_NAME}_words_ref.txt \
--gold_processed ${DATA_DIR}/zgen_data_npsyms_freq3_unkUNK/no_npsyms/${SPLIT_NAME}_words_no_eos.txt \
--out_file ${OUTPUT_FILE}_removed_unk.txt \
--remove_npsyms

echo "####" >> ${OUTPUT_LOG_FILE}
echo ${LABEL} >> ${OUTPUT_LOG_FILE}

${REPO_DIR}/analysis/eval/zgen_bleu/ScoreBLEU.sh -t ${OUTPUT_FILE}_removed_unk.txt -r ${DATA_DIR}/zgen_data_gold/${SPLIT_NAME}_words_ref.txt -odir ${TEMP_DIR} >> ${OUTPUT_LOG_FILE}
